### PR TITLE
Support ratings out of 5 instead of out of 10

### PR DESCRIPTION
**Pull request by contactashish13**
#252

### CODE REVIEW

**Comment by radu-themeisle** [comment]
@contactashish13 if you set the rating to 5 stars the "rating through comment" should also allow the slider/star rating to go only to 5. Now it still based on the scale of 10: http://prntscr.com/o0d3sf
I'd also think that when star rating is enabled for comments it would be better to either use stars instead of radio buttons or, even better, the icon that the user chooses (for Pro of course)

**Comment by contactashish13** [comment]
@radu-themeisle 

> if you set the rating to 5 stars the "rating through comment" should also allow the slider/star rating to go only to 5. Now it still based on the scale of 10: 

I don't want to force users. They have the flexibility to use whatever system they want.

You should see golden stars (cannot show the custom icon) instead of the radio buttons. Can you refresh your cache or see if there was a JS error in the console?

**Comment by contactashish13** [comment]
@radu-themeisle did you get a chance to test this again? It should look like this

image

**Comment by radu-themeisle** [comment]
@contactashish13 I tested again and I can happily say it looks good 👌

I managed to see the star rating by changing the option for **Comment rating style** from the settings to star rating (it was set to slider so that's why I didn't see the stars). I'll have to keep in mind to write this in the docs.


Thank you for changing the rating scale for comment reviews like I previously asked, meaning that now if your rating is based on a scale to 5 the comment rating will be based on the same scale.
I also like that you can select half-stars and full stars in the comment review.

I'd ask for 2 _enhancements_ if it's not too much trouble:

1. Make the options' rating scale in comment reviews increment by 0.5: Basically users will have a simpler choice like: 1, 1.5, 2, 2.5 etc.
This would be inline with the star review which only let's you select none, half-star and full-star.
Right now, if you have the slider rating for comments you can move the rating in 0.05 steps which seems unnecessarily granular and simplifying the user's choice would improve the experience (most of the big eCommerce companies use simplified choices for star ratings).

2. While using star rating for review comments when you hover over the stars the [mouse's icon](http://prntscr.com/o6r4z4) should turn into a pointer icon (it only does for the slider  rating).

**Pull request merged**
