### PR TITLE
Support different review types/schemas

### PR DESCRIPTION
**Pull request by contactashish13**
#322

### CODE REVIEW

**Comment by selul** [comment]
@contactashish13 it has been a new release for WordPress coding standards, can you try to update your local one, run phpcbf and see if is fixed?

**Comment by contactashish13** [comment]
@selul I did that and the errors reported by travis are different from what phpcs reports at my end (line endings only). I'm not sure what to do. Should I exclude those rules from phpcs?

**Comment by selul** [comment]
Yes, let's exclude those rules.

**Comment by contactashish13** [comment]
@selul can you please check why travis is failing? 

image

**Comment by selul** [comment]
@contactashish13 it seems to work ok now, i've updated the npm deps using npm update and seems to be solving the issue.

**Pull request merged**
