### PR TITLE
Release 3.5.0

### PR DESCRIPTION
**Pull request by rodica-andronache**

### CODE REVIEW

**Comment by HardeepAsrani** [comment]
Nope, it only shows me the Sidebar. o.O

**Comment by HardeepAsrani** [comment]
@rodica-andronache Can you ask someone else to try?

**Comment by rodica-andronache** [comment]
@HardeepAsrani sure :D I tested again, and this time, for me the options appear just in the content http://prntscr.com/ktz7v4
Maybe @LamaBabana would like to test too :)

**Comment by HardeepAsrani** [comment]
@rodica-andronache It's little confusing because that integration is made for post-5.0, and we're using it in a world where Gutenberg is a plugin. Can you make an online website so I can exactly see? It works for me.

**Comment by HardeepAsrani** [comment]
Also make sure to test here: https://github.com/Codeinwp/wp-product-review/pull/314

**Comment by LamaBabana** [comment]
I have just tested this as well. Looks like the options are available only from the sidebar for me. 

- New post -> http://prntscr.com/kvqavv

- Already existing post -> http://prntscr.com/kvqbyj

**Comment by rodica-andronache** [comment]
@HardeepAsrani it's ok for me too, I was testing this PR, not #314 👍 
For me, if @LamaBabana can test #314 it a bit further, check all the options from lite and pro too, this should be updated.
cc @contactashish13

**Pull request closed without merging**
