### PR TITLE
Updated Gutenberg Sidebar - TEST EXTENSIVELY

### PR DESCRIPTION
**Pull request by HardeepAsrani**
Fixed: https://github.com/Codeinwp/wp-product-review/issues/313

Make sure to test this extensively as Node made my container slow and couldn't test it enough, but worked perfectly for me. @rodica-andronache

### CODE REVIEW

**Comment by HardeepAsrani** [comment]
To be noted, if you have both Gutenberg and TinyMCE (which is the only way to use Gutenberg right now), the meta boxes won't appear in Classic Editor but Gutenberg only. If you can find a better way to do it then let me know.

**Comment by HardeepAsrani** [comment]
Updated with Import Review (preloader, is it called?) in Pro version. You can find that option in the bottom of the sidebar when you've Pro version activated.

**Comment by HardeepAsrani** [comment]
FYI, here's how you Import Reviews with Pro version:

sep-30-2018 23-56-36

**Comment by HardeepAsrani** [comment]
Would be awesome if @SilviuDinu could do the tests, also would be even awesome if he can post a video if there's an issue. :)

**Comment by HardeepAsrani** [comment]
Closed by mistake. :D

**Comment by SilviuDinu** [comment]
I've been testing this while the WordPress Beta Tester plugin was both active or not. When it wasn't active, all worked well (http://prntscr.com/lo0tv4). The options were all there even after returning to the post in the dashboard. With the Beta Tester on, some of the notices are brought to front for some reason, but I don't think this is related to WPPR (screenshot -> http://prntscr.com/lo0mos)

**Comment by HardeepAsrani** [comment]
@SilviuDinu Those notices are due to Orbit Fox, and aren't an issue.

**Comment by contactashish13** [comment]
@HardeepAsrani can you resolve the conflicts here?

**Comment by HardeepAsrani** [comment]
@contactashish13 There you go.

**Pull request merged**
