### PR TITLE
[WiP]: Migration for Otter

### PR DESCRIPTION
**Pull request by HardeepAsrani**
Otter 1.6.5 was released on Friday and it contains Product Review Block. We need to test review migration to see everything migrates properly.

Here's what has changed in this PR:

- If you have a post with a saved Product Review, you get a Migrate button when you open add a Product Review Block. If you click the data of Review is prefilled.
- Similarly, in the WPPR sidebar in Editor, you get a migration button that adds a Product Review Block to the editor.

Make sure everything works fine. Don't click on disable button as it will disable it until you toggle it from the dashboard.

### CODE REVIEW

**Comment by HardeepAsrani** [comment]
Can you test this @irinelenache? Details in the issue.

**Comment by irinelenache** [comment]
@HardeepAsrani 

- [ ] if i migrate using the **Migrate to Block** button (https://prnt.sc/13cdya8), the product features aren't migrated and the block comes with the default ones
wppr:  https://prnt.sc/13cctyt
product block: https://prnt.sc/13cdnar

**Comment by HardeepAsrani** [comment]
@irinelenache Can you try doing it on Jurassic Ninja so I can test?

**Comment by irinelenache** [comment]
@HardeepAsrani can you tell me which are the commands for creating the zip file? i tested only with local

**Comment by HardeepAsrani** [comment]
Sent on Slack.

**Comment by irinelenache** [comment]
@HardeepAsrani the product features are migrated now 👍 
found something else:

- [ ] in wppr, if i have the button link set without `https://` (like this https://prnt.sc/13ft32f) it works fine, but after i migrate it, the link is not transferred correctly https://prnt.sc/13ft63m

**Comment by HardeepAsrani** [comment]
@irinelenache Not an issue with this PR but with Product Review Block which we will fix separately. Anything else?

**Comment by irinelenache** [comment]
@HardeepAsrani besides of that, it works fine

**Pull request merged**
