### PR TITLE
add frontend review submission for review cpts

### PR DESCRIPTION
**Pull request by contactashish13**

### CODE REVIEW

**Comment by rodica-andronache** [comment]
@contactashish13 I tested this with https://github.com/Codeinwp/wp-product-review-pro/pull/96 but I can't figure it out how to make the shortcode to display. Am I missing something? :)

**Comment by contactashish13** [comment]
@rodica-andronache took me a long time to remember this as well :) This feature is only for business users otherwise the add on will not load.

**Comment by rodica-andronache** [comment]
@contactashish13 thanks 👍 
is looking good for me, @rohittm could you please test this too? Make sure you test both with all the options in the form and with some of them empty.

@contactashish13 just a few suggestions:
When the review cpt is not enabled, the message is "Custom post type not enabled". Maybe it would be more suggesting something like "The Review custom post type is not enabled." with a link to the page where that can be done.

Is there any way to add the Review custom post type in the menu once you save the options with the ‘Enable review post type’ option true? Or at least refresh the page. It’s confusing to don’t see what happened after saving the changes.

What do you say about adding a title parameter to the shortcode?

**Comment by contactashish13** [comment]
@rodica-andronache 

1. have added "The Review custom post type is not enabled. You can enable this in the settings page."
2. have added "Enabling this will create a new post type where you can manage your reviews. Refresh the page on saving changes to see the "Reviews" menu on the left." to the settings page so that it is no longer confusing.
3. what would the title parameter do?

**Comment by contactashish13** [comment]
@rodica-andronache wouldn't the post title be enough for that?

**Comment by rodica-andronache** [comment]
@contactashish13 I would like to add the title parameter too, if it's not too difficult :)

**Comment by contactashish13** [comment]
@rodica-andronache done.

**Comment by contactashish13** [comment]
@rohittm add the shortcode `[wppr_submit_review]` or `[wppr_submit_review title='xxx']` and you will get the form to submit a review. This shortcode will only work when the review post type is on. This review will be available as a draft in the back end.

**Pull request merged**
