### PR TITLE
fix issue with buy button in listing table

### PR DESCRIPTION
**Pull request by HardeepAsrani**

### CODE REVIEW

**Comment by contactashish13** [comment]
@HardeepAsrani can you clear the conflict? Also, I don't think you should be checking in the lock file

**Comment by HardeepAsrani** [comment]
@contactashish13 Don't know why it was even commiting.

**Comment by HardeepAsrani** [comment]
@contactashish13 I run `grunt local` and `phpcs` runs clean, while on Travis it gives tons of errors. phpcs.xml is same in clone and source. Any pointers?

**Comment by selul** [comment]
@HardeepAsrani do you have the latest phpcs installed locally?

**Comment by contactashish13** [comment]
@HardeepAsrani new WPCS rules came out last week so you may need to upgrade your WPCS

**Comment by HardeepAsrani** [comment]
```Use strict comparisons (=== or !==)```

@contactashish13 Should I turn off this warning? There is a lot of warning for strict comparisons and it will be difficult for me to test each line to check the data type.

**Comment by contactashish13** [comment]
@HardeepAsrani if you sync with the branch called `3.6.0` and then run grunt, it should all be good

**Comment by HardeepAsrani** [comment]
@contactashish13 3.6.0 doesn't have any code changes. Merged that and it's the same.

**Comment by contactashish13** [comment]
@HardeepAsrani sorry, I had made these changes as part of #365 and once I merge them to 3.6.0 you should get those changes as well. I'll let you know when.

**Comment by contactashish13** [comment]
@HardeepAsrani you can now sync with branch 3.6.0

**Comment by HardeepAsrani** [comment]
@contactashish13 Done sir!

**Pull request merged**
